services:
  design.general.scope.social_media_settings:
    class: VPyatin\Bundle\PyatinThemeBundle\Config\SocialMediaSettingsManager
    public: false
    parent: oro_config.scope_manager.abstract
    tags:
      - { name: oro_config.scope, scope: social_media_settings, priority: 50 }

  design.general.provider.form_provider.social_media_settings:
    class: 'VPyatin\Bundle\PyatinThemeBundle\Provider\SocialMediaSettingsFormProvider'
    parent: 'oro_config.provider.abstract_provider'
    lazy: true