system_configuration:
    groups:
        pyatin_core_settings:
            title: oro.config.system_configuration.groups.core_settings.title
            icon: fa-key
        pyatin_core_settings_general:
            title: oro.config.system_configuration.groups.core_settings.general.title
            icon: fa-keyboard-o

    fields:
        core.currency_exchange_api_url:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\UrlType'
            priority: 10
            options:
                label: oro.config.system_configuration.groups.core_settings.currency_exchange.api_url.title

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            pyatin_core_settings:
                                children:
                                    pyatin_core_settings_general:
                                        priority: 5
                                        children:
                                            - core.currency_exchange_api_url

