services:
  VPyatin\Bundle\UserNamingBundle\Provider\UserNamingProviderDecorator:
    decorates: oro_locale.entity_name_provider
    arguments:
      - '@.inner'
    tags:
      - { name: oro_entity.name_provider, priority: -60 }

  VPyatin\Bundle\UserNamingBundle\Controller\Frontend\NamingController:
    autowire: true
    autoconfigure: true
    calls:
      - [ 'setContainer', [ '@service_container' ] ]
    tags:
      - { name: container.service_subscriber }